name: THIRST
favicon: null
layout_spectrum: 0.9140734707470983
typography_spectrum: 0.9155468174722046
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9648337892722338
  lightness: 0.5662887690123171
  saturation: 0.9798311430495232
  rhythmicContrast: 0.5527619202621281
purpose: []
