name: THIRST
favicon: null
layout_spectrum: 0.9140734707470983
typography_spectrum: 0.9155468174722046
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#878883'
    - '#791b23'
    - '#a4a4a1'
    - '#bfbfbc'
  brandStrength: 0.5
  lightness: 0.5662887690123171
  saturation: 0.9798311430495232
  rhythmicContrast: 0.5527619202621281
purpose: []
